### ISSUE TITLE
Cannot read property 'el' of undefined

### ISSUE THREAD

**Issue by coderdiaz** [helpbase/vue-froala#1]
We has followed your instructions as you say and we get this issue.
![Issue](https://cloud.githubusercontent.com/assets/1901273/21236874/44006c8c-c2c2-11e6-9822-f2ed86888eea.JPG)

Does It's necessary to use **RollUp** for compile it? Because we are using **Webpack**

**Comment by whitef0x0** [comment]
@coderdiaz are you trying to get the demo running?

**Comment by coderdiaz** [comment]
Hi @whitef0x0 
Yes, but isn't working :(

**Comment by gggso** [comment]
froala-editor 2.4.0

**Comment by gggso** [comment]
![image](https://cloud.githubusercontent.com/assets/6212790/21306878/1954d2ee-c60e-11e6-99c3-a25c665ac02f.png)

**Comment by whitef0x0** [comment]
@ggso I'll post a working example later in the week

**Comment by coderdiaz** [comment]
Thanks @whitef0x0 👍

**Comment by lmiller1990** [comment]
Same problem here. Any progress on this? I am using Vue 2+

**Comment by coderdiaz** [comment]
Nothing so far :(

**Comment by drozdzynski** [comment]
In vue 2+ still not work :/

**Comment by whitef0x0** [comment]
@drozdzynski @coderdiaz Just fixed it.

**Comment by whitef0x0** [comment]
Moved from a directive to a component.

**Comment by coderdiaz** [comment]
Thanks @whitef0x0 👍
